application: pintme
version: 2
runtime: python
api_version: 1

handlers:
- url: /controllers
  static_dir: controllers
  
- url: /views
  static_dir: views
  
# Index page and post request handle by main.py
- url: /
  script: controllers/main.py
  
- url: /index.*
  script: controllers/main.py
  
- url: /(post|register)
  script: controllers/main.py
  
# Account Setting page and post config request handle by account_settings.py
- url: /account_settings
  script: controllers/account_settings.py
  
- url: /account_settings/post
  script: controllers/account_settings.py
