application: pintme
version: 2
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: stylesheets
    
# Index page and post requests handle by main.py
- url: /
  script: main.py
  
- url: /(post|register)
  script: main.py
  
# Account Setting page and post config requests handle by account_settings.py
- url: /account_settings
  script: account_settings.py
  
- url: /account_settings/post
  script: account_settings.py
  
# Search results page and profil page
- url: /search
  script: search.py
  
- url: /profil/.*
  script: profil.py
  
- url: /profil/post
  script: profil.py
