application: pintme
version: 3
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: public/stylesheets
  
- url: /images
  static_dir: public/images

- url: /admin.*
  script: index.py
  login: admin

- url: .*
  script: index.py