application: pintme
version: 2
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: public/stylesheets
  
- url: /images
  static_dir: public/images

- url: /
  script: index.py
  
- url: /(post|register|compose|settings|down)
  script: index.py