#!/usr/bin/env python
#
# Copyright 2009 Simon&Humphries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from models import Title

def generate_titles():
	Title(title='<a>PINT</a>Spot').put()
	Title(title='<a>PINT</a>ed').put()
	Title(title='<a>PINT</a>Me').put()
	Title(title='<a>PINT</a>Soft').put()
	Title(title='<a>PINT</a>Hard').put()
	Title(title='<a>PINT</a>SM').put()
	Title(title='<a>PINT</a>ware').put()
	Title(title='<a>PINT</a>BDSM').put()
	Title(title='<a>PINT</a>BSD').put()
	Title(title='<a>PINT</a>LSD').put()
	Title(title='<a>PINT</a>ou (or ubuntu)').put()
	Title(title='<a>PINT</a>ubuntu').put()
	Title(title='i<a>PINT</a>').put()
	Title(title='you<a>PINT</a>').put()
	Title(title='Google <a>PINT</a>').put()
	Title(title='<a>PINT</a>Please').put()
	Title(title='<a>PINT</a>Sorry').put()
	Title(title='<a>PINT</a>Welcomed').put()
	Title(title='<a>PINT</a>Again').put()
	Title(title='<a>PINT</a>guin').put()
	Title(title='JustOne<a>PINT</a>').put()
	Title(title='JustAnother<a>PINT</a>').put()
	Title(title='OneMore<a>PINT</a>').put()
	Title(title='Bier&<a>PINT</a>').put()
	Title(title='<a>PINT</a>OfVodka').put()
	Title(title='<a>PINT</a>ade').put()
	Title(title='<a>PINT</a>aid').put()
	Title(title='<a>PINT</a>ADD').put()
	Title(title='<a>PINT</a>INC').put()
	Title(title='<a>PINT</a>agramme').put()
	Title(title='<a>PINT</a>-A-Gramme').put()
	Title(title='<a>PINT</a>-A-Kilo').put()
	Title(title='Pound-A-<a>PINT</a>').put()
	Title(title='Fish<a>PINT</a>').put()
	Title(title='<a>PINT</a>Sized').put()
	Title(title='Mystic<a>PINT</a>').put()
	Title(title='Super<a>PINT</a>').put()
	Title(title='Hyper<a>PINT</a>').put()
	Title(title='Quantic<a>PINT</a>').put()
	Title(title='QuantumOf<a>PINT</a>').put()
	Title(title='Electro<a>PINT</a>').put()
	Title(title='Royal<a>PINT</a>').put()
	Title(title='Republican<a>PINT</a>').put()
	Title(title='YesWeCan...<a>PINT</a>').put()
	Title(title='WhatTheFucking...<a>PINT</a>').put()
	Title(title='IVotedFor<a>PINT</a>').put()
	Title(title='WhatSThe<a>PINT</a>').put()
	Title(title='<a>PINT</a>Aday').put()
	Title(title='<a>PINT</a>IsMine').put()
	Title(title='my<a>PINT</a>!').put()
	Title(title='<a>PINT</a>Book').put()
	Title(title='<a>PINT</a>Book-Air').put()
	Title(title='less Air more <a>PINT</a>').put()
	Title(title='Apple<a>PINT</a>').put()
	Title(title='Web<a>PINT</a>').put()
	Title(title='Command+<a>PINT</a>').put()
	Title(title='Ctrl+Meta+Alt+<a>PINT</a>').put()
	Title(title=':<a>PINT</a>').put()
	Title(title='3Click<a>PINT</a>').put()
	Title(title='Black<a>PINT</a>').put()
	Title(title='<a>PINT</a>sh').put()
	Title(title='<a>PINT</a> (<a>PINT</a> Is Not Twilight)').put()
	Title(title='tinP').put()
	Title(title='tniP').put()
	Title(title='Tonight<a>PINT</a>').put()
	Title(title='Coffee<a>PINT</a>').put()
	Title(title='Breakfast<a>PINT</a>').put()
	Title(title='Bacon<a>PINT</a>').put()
	Title(title='<a>PINT</a>Pause').put()
	Title(title='<a>PINT</a>-nic').put()
	Title(title='<a>PINT</a>Address').put()
	Title(title='<a>PINT</a>Phone').put()
	Title(title='Multi<a>PINT</a>').put()
	Title(title='Simple<a>PINT</a>...').put()
	Title(title='FourFingers<a>PINT</a>').put()
	Title(title='Start<a>PINT</a>').put()
	Title(title='Stop<a>PINT</a>').put()
	Title(title='<a>PINT</a>').put()
	Title(title='<a>PINT</a>EGER').put()
	Title(title='FloatOr<a>PINT</a>').put()
	Title(title='<a>PINT</a>Pointer').put()
	Title(title='Master<a>PINT</a>er').put()
	Title(title='License<a>PINT</a>er').put()
	Title(title='GNU<a>PINT</a>').put()
	Title(title='<a>PINT</a>ix').put()
	Title(title='<a>PINT</a>ux').put()
	Title(title='<a>PINT</a>ium').put()
	Title(title='<a>PINT</a>OS').put()
	Title(title='ThanksForThe<a>PINT</a>').put()
	Title(title='LordOfThe<a>PINT</a>').put()
	Title(title='Piss<a>PINT</a>').put()
	Title(title='<a>PINT</a>8').put()
	Title(title='666 Number Of The <a>PINT</a>').put()
	Title(title='Bug<a>PINT</a>').put()
	Title(title='BlueScreenOf<a>PINT</a>').put()
	Title(title='<a>PINT</a>Panic').put()
	Title(title='<a>PINT</a>OSleep').put()
	Title(title='<a>PINT</a>craft').put()
	Title(title='War<a>PINT</a>').put()
	Title(title='<a>PINT</a>OfDead').put()
	Title(title='<a>PINT</a>sOfTheCaribeans').put()
	Title(title='TheLast<a>PINT</a>').put()
	Title(title='<a>PINT</a>:Revolution').put()
	Title(title='<a>PINT</a>:Resurrection').put()
	Title(title='Evil<a>PINT</a>').put()
	Title(title='TheIncredible<a>PINT</a> ').put()
	Title(title='X<a>PINT</a> ').put()
	Title(title='Y<a>PINT</a>').put()
	Title(title='Why<a>PINT</a>').put()
	Title(title='Inexhaustible<a>PINT</a>').put()
	Title(title='SauronS<a>PINT</a>').put()
	Title(title='Sleepy<a>PINT</a>').put()
	Title(title='NeverSleep<a>PINT</a>').put()
	Title(title='<a>PINT</a>Wars').put()
	Title(title='P1N7').put()
	Title(title='<a>PINT</a> in PAL/SECAM').put()